### PR TITLE
changed local to external

### PR DESCRIPTION
**Pull request by lsizemore8**
Due to the packr not working on Mac, I updated GameEngine to use external instead of local.

### CODE REVIEW

**Comment by lsizemore8** [comment]
@ravinapatel, please test this by seeing if your local save.json is updated in the correct folder (so not the savedata in core/assets)
@ronnie-dumesh, please test this by creating a jar and opening it by clicking, you are the only one who hit the bug w/ the level unlocking, so you need to test this.

**Comment by BryanGraeser** [comment]
Where is this file written? I can't find it

**Comment by BryanGraeser** [comment]
I literally cannot find it. I deleted every `save.json` I could find and it's still running, so idk where it is.

**Comment by BryanGraeser** [comment]
Ok nevermind, it goes to your $HOME directory. @lsizemore8 can you remove all the old outdates save.json files and savedata folders now? And I think this should be tested by mac users before merging.

**Review by BryanGraeser — APPROVED** [review]
gtg (assuming someone on Mac tests)

**Pull request merged**
