### PR TITLE
Animated light that fades in and fades out

### PR DESCRIPTION
**Pull request by foxhatleo**
This PR adds an animation effect to light that when light source starts or dies because of flare or enemy, a quick tween of the radius is automatically applied so it doesn't look too sudden.

### CODE REVIEW

**Comment by BryanGraeser** [comment]
I'm getting this error: 
`LightController.java:107: error: cannot find symbol
                           JsonValue levelLighting, World world, Rectangle bounds, Vector2 scale) {
                                                                                   ^
  symbol:   class Vector2
  location: class LightController`

**Comment by BryanGraeser** [comment]
> 
> 
> I'm getting this error:
> `LightController.java:107: error: cannot find symbol JsonValue levelLighting, World world, Rectangle bounds, Vector2 scale) { ^ symbol: class Vector2 location: class LightController`

Added import statement

**Review by BryanGraeser — APPROVED** [review]
Wow this looks really nice! Definitely improves the feel.

**Comment by foxhatleo** [comment]
> Wow this looks really nice! Definitely improves the feel.

Thanks. Sorry, the error was from a merge conflict that was poorly handled by me.

**Pull request merged**
