### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by BryanGraeser**
UI updates (excluding level select which Max is working on)

### CODE REVIEW

**Comment by lsizemore8** [comment]
Writing this here so I can fix it in the morning. Menu screen needs to be updated: Start and Select should be combined to just be "play"

**Review by ravinapatel — APPROVED** [review]

**Review by BryanGraeser — COMMENTED** [review]
I think we need to add 'pause' to the controls screen before merging

**Review by lsizemore8 — CHANGES_REQUESTED** [review]
If you change Pause to something else, you then cannot change it back to 'esc'

**Comment by BryanGraeser** [comment]
Contemplating changing pause to 'p' and never allowing 'esc' pausing

**Comment by lsizemore8** [comment]
If you press "reset to default", pause goes back to being escape instead of p

**Review by lsizemore8 — APPROVED** [review]
Looks gtg

**Pull request merged**
