### PR TITLE
Laura level

### PR DESCRIPTION
**Pull request by lsizemore8**
image

### CODE REVIEW

**Comment by BryanGraeser** [comment]
JSON stuff looks good. Haven't playtested yet, but just wanted to comment that

**Comment by BryanGraeser** [comment]
Played it and it seems fine. Tbh is a little easy, but we could just have it as an earlier level (also it may be bc I've played our game so much lol)

**Comment by lsizemore8** [comment]
Yeah that was intentional. I wanted an easier level to be added so we can have a greater range. Will deal with the merge conflicts now/merge it if you can approve it

**Review by BryanGraeser — APPROVED** [review]
Technically looks gtg (I resolved merge conflicts). I think it is maybe a little easy and also you call it "force sneak," but if this was the intent I don't think it forces sneak (you can just fire a flare right at the start). If you want to force sneak, maybe start the player with no flares and have them pick them up in the middle of the level, this would also increase difficulty and add another level that uses pickups.

**Comment by BryanGraeser** [comment]
Your choice if you want to make any level design changes before merging

**Comment by lsizemore8** [comment]
Oooh good point. Yeah I'll update that after my next class.

**Comment by BryanGraeser** [comment]
Talked with Laura, merging now and later PR for level design changes.

**Pull request merged**
